pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                withEnv(["MAVEN_HOME=/opt/apache-maven-3.9.4"]) {
                    script {
                        // Ensure Maven is in the PATH
                        env.PATH = "${MAVEN_HOME}/bin:${env.PATH}"
                        // Run Maven commands
                        sh 'mvn -B -DskipTests clean build package'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
